### ISSUE TITLE
open3d error

### ISSUE THREAD

**Issue by Ivanyan0516** [POSTECH-CVLab/point-transformer#15]
OSError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/ma-user/work/yanfan/envs/pt/lib/python3.6/site-packages/open3d/cpu/pybind.cpython-36m-x86_64-linux-gnu.so)

how can i solve this?please 
change open3d == 0.12.0 ,0.11.0,0.9.0  still does not work

**Comment by codebyzhp** [comment]
> OSError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/ma-user/work/yanfan/envs/pt/lib/python3.6/site-packages/open3d/cpu/pybind.cpython-36m-x86_64-linux-gnu.so)
> 
> how can i solve this?please
> change open3d == 0.12.0 ,0.11.0,0.9.0 still does not work

What system are you using. I had a similar problem on Centos7
```
OSError: /lib64/libc.so.6: version `GLIBC_2.18' not found 
```
I tossed for a long time, and later reduced the open3d version，by
+ `pip uninstall open3d`
+ `conda install -c open3d-admin open3d==0.9`

Hope it helps you！

**Comment by chrockey** [comment]
Hi,

Sorry for the late reply.
I'm also aware that there is an incompatibility of open3d with Centos.
Please try Ubuntu for this repository.

Regards,

Chunghyun
