### ISSUE TITLE
Hi, there!

### ISSUE THREAD

**Issue by yuchenlichuck** [POSTECH-CVLab/point-transformer#19]
Thanks for your upload; I found you have already gotten the result based on the point transformer. But your now source code looks not like the implementation of point transformer. Will you update the source code? Thank you!

**Comment by chrockey** [comment]
Hi,

Sorry for the late reply.
We just have been provided source codes for S3DIS experiments from the first author of [Point Transformer](https://arxiv.org/abs/2012.09164).
It looks pretty consistent with the illustration of the paper.
Could you try with the updated master branch?

Regrads,

Chunghyun

**Comment by chrockey** [comment]
If you have any questions, please create another issue.

**Comment by yuchenlichuck** [comment]
Thank you so much!
