### ISSUE TITLE
Building error with point_transformer_ops

### ISSUE THREAD

**Issue by whuhxb** [POSTECH-CVLab/point-transformer#20]
Hi, 
I use python 3.7, cuda10.1, pytorch 1.7.1 to build the point_transformer_ops, but there are a lot of errors. It uses the default CUDA 9.0, and the compling has error with     nvcc fatal   : Unsupported gpu architecture 'compute_75'.  How to deal with these errors? Thanks.

    No CUDA runtime is found, using CUDA_HOME='/cm/shared/apps/cuda90/toolkit/9.0.176'
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/point_transformer_ops
    copying point_transformer_ops/__init__.py -> build/lib.linux-x86_64-3.7/point_transformer_ops
    copying point_transformer_ops/point_transformer_modules.py -> build/lib.linux-x86_64-3.7/point_transformer_ops
    copying point_transformer_ops/_version.py -> build/lib.linux-x86_64-3.7/point_transformer_ops
    copying point_transformer_ops/point_transformer_utils.py -> build/lib.linux-x86_64-3.7/point_transformer_ops
    running egg_info
    writing point_transformer_ops.egg-info/PKG-INFO
    writing dependency_links to point_transformer_ops.egg-info/dependency_links.txt
    writing requirements to point_transformer_ops.egg-info/requires.txt
    writing top-level names to point_transformer_ops.egg-info/top_level.txt
    reading manifest file 'point_transformer_ops.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'point_transformer_ops.egg-info/SOURCES.txt'
    creating build/lib.linux-x86_64-3.7/point_transformer_ops/_ext-src
    creating build/lib.linux-x86_64-3.7/point_transformer_ops/_ext-src/include
    copying point_transformer_ops/_ext-src/include/ball_query.h -> build/lib.linux-x86_64-3.7/point_transformer_ops/_ext-src/include
    copying point_transformer_ops/_ext-src/include/cuda_utils.h -> build/lib.linux-x86_64-3.7/point_transformer_ops/_ext-src/include
    copying point_transformer_ops/_ext-src/include/group_points.h -> build/lib.linux-x86_64-3.7/point_transformer_ops/_ext-src/include
    copying point_transformer_ops/_ext-src/include/interpolate.h -> build/lib.linux-x86_64-3.7/point_transformer_ops/_ext-src/include
    copying point_transformer_ops/_ext-src/include/sampling.h -> build/lib.linux-x86_64-3.7/point_transformer_ops/_ext-src/include
    copying point_transformer_ops/_ext-src/include/utils.h -> build/lib.linux-x86_64-3.7/point_transformer_ops/_ext-src/include
    creating build/lib.linux-x86_64-3.7/point_transformer_ops/_ext-src/src
    copying point_transformer_ops/_ext-src/src/ball_query.cpp -> build/lib.linux-x86_64-3.7/point_transformer_ops/_ext-src/src
    copying point_transformer_ops/_ext-src/src/ball_query_gpu.cu -> build/lib.linux-x86_64-3.7/point_transformer_ops/_ext-src/src
    copying point_transformer_ops/_ext-src/src/bindings.cpp -> build/lib.linux-x86_64-3.7/point_transformer_ops/_ext-src/src
    copying point_transformer_ops/_ext-src/src/group_points.cpp -> build/lib.linux-x86_64-3.7/point_transformer_ops/_ext-src/src
    copying point_transformer_ops/_ext-src/src/group_points_gpu.cu -> build/lib.linux-x86_64-3.7/point_transformer_ops/_ext-src/src
    copying point_transformer_ops/_ext-src/src/interpolate.cpp -> build/lib.linux-x86_64-3.7/point_transformer_ops/_ext-src/src
    copying point_transformer_ops/_ext-src/src/interpolate_gpu.cu -> build/lib.linux-x86_64-3.7/point_transformer_ops/_ext-src/src
    copying point_transformer_ops/_ext-src/src/sampling.cpp -> build/lib.linux-x86_64-3.7/point_transformer_ops/_ext-src/src
    copying point_transformer_ops/_ext-src/src/sampling_gpu.cu -> build/lib.linux-x86_64-3.7/point_transformer_ops/_ext-src/src
    running build_ext
    building 'point_transformer_ops._ext' extension
    creating /tmp/pip-req-build-comdcmt1/build/temp.linux-x86_64-3.7
    creating /tmp/pip-req-build-comdcmt1/build/temp.linux-x86_64-3.7/point_transformer_ops
    creating /tmp/pip-req-build-comdcmt1/build/temp.linux-x86_64-3.7/point_transformer_ops/_ext-src
    creating /tmp/pip-req-build-comdcmt1/build/temp.linux-x86_64-3.7/point_transformer_ops/_ext-src/src
    Emitting ninja build file /tmp/pip-req-build-comdcmt1/build/temp.linux-x86_64-3.7/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    [1/9] /cm/shared/apps/cuda90/toolkit/9.0.176/bin/nvcc -I/tmp/pip-req-build-comdcmt1/point_transformer_ops/_ext-src/include -I/export/home/hanxiaobing/anaconda3/envs/pytorch-Point-Transformer/lib/python3.7/site-packages/torch/include -I/export/home/hanxiaobing/anaconda3/envs/pytorch-Point-Transformer/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/export/home/hanxiaobing/anaconda3/envs/pytorch-Point-Transformer/lib/python3.7/site-packages/torch/include/TH -I/export/home/hanxiaobing/anaconda3/envs/pytorch-Point-Transformer/lib/python3.7/site-packages/torch/include/THC -I/cm/shared/apps/cuda90/toolkit/9.0.176/include -I/export/home/hanxiaobing/anaconda3/envs/pytorch-Point-Transformer/include/python3.7m -c -c /tmp/pip-req-build-comdcmt1/point_transformer_ops/_ext-src/src/interpolate_gpu.cu -o /tmp/pip-req-build-comdcmt1/build/temp.linux-x86_64-3.7/point_transformer_ops/_ext-src/src/interpolate_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -Xfatbin -compress-all -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_37,code=sm_37 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_62,code=sm_62 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_37,code=compute_37 -std=c++14
    FAILED: /tmp/pip-req-build-comdcmt1/build/temp.linux-x86_64-3.7/point_transformer_ops/_ext-src/src/interpolate_gpu.o
    /cm/shared/apps/cuda90/toolkit/9.0.176/bin/nvcc -I/tmp/pip-req-build-comdcmt1/point_transformer_ops/_ext-src/include -I/export/home/hanxiaobing/anaconda3/envs/pytorch-Point-Transformer/lib/python3.7/site-packages/torch/include -I/export/home/hanxiaobing/anaconda3/envs/pytorch-Point-Transformer/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/export/home/hanxiaobing/anaconda3/envs/pytorch-Point-Transformer/lib/python3.7/site-packages/torch/include/TH -I/export/home/hanxiaobing/anaconda3/envs/pytorch-Point-Transformer/lib/python3.7/site-packages/torch/include/THC -I/cm/shared/apps/cuda90/toolkit/9.0.176/include -I/export/home/hanxiaobing/anaconda3/envs/pytorch-Point-Transformer/include/python3.7m -c -c /tmp/pip-req-build-comdcmt1/point_transformer_ops/_ext-src/src/interpolate_gpu.cu -o /tmp/pip-req-build-comdcmt1/build/temp.linux-x86_64-3.7/point_transformer_ops/_ext-src/src/interpolate_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -Xfatbin -compress-all -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_37,code=sm_37 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_62,code=sm_62 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_37,code=compute_37 -std=c++14
    nvcc fatal   : Unsupported gpu architecture 'compute_75'

**Comment by chrockey** [comment]
Hi,

Sorry for the late reply.
The error message shows that you have used not cuda 10.1 but cuda 9.0, which is not compatible with your GPU, to compile cuda kernels.

However, we just updated our codebase with the codes from the first author of [Point Transformer](https://arxiv.org/abs/2012.09164) and confirmed that cuda kernels can be successfully compiled with it.
Please try the updated codebase.

Regards,

Chunghyun
