### ISSUE TITLE
Empty S3DIS data link

### ISSUE THREAD

**Issue by densechen** [POSTECH-CVLab/point-transformer#25]
Hi, thanks for providing nice code.
But the Google Driver Link is empty, Can you provide a new link?
I also find the dataset from PAConv, which link is also invalid.

**Comment by chrockey** [comment]
Hi,

Sorry for the late reply.
We've just updated the download link, and you can use it.

As you have founded, we use the same dataset with [PAConv repo](https://github.com/CVMI-Lab/PAConv).
