### ISSUE TITLE
How many points are used for shape classification on the ModelNet40 in training phase?

### ISSUE THREAD

**Issue by DapengFeng** [POSTECH-CVLab/point-transformer#33]
Thanks for your excellent work. I get a question about the number of points used for shape classification on the ModelNet40 after reading the paper.

**Comment by moshicaixi** [comment]
usually, 1024 for classification, 2048 for segmentation. This is my experience.

**Comment by DapengFeng** [comment]
Thanks for your reply.

**Comment by chengsilin** [comment]
Can you reproduce the results reported by paper?

**Comment by DapengFeng** [comment]
> Can you reproduce the results reported by paper?

No, I just read some papers about point transformer recently
