### ISSUE TITLE
Clarification for pointops.queryandgroup function

### ISSUE THREAD

**Issue by ktertikas** [POSTECH-CVLab/point-transformer#41]
Hello, thank you for the clean codebase! I have a question regarding the `pointops.queryandgroup` function. In particular, in the following line, we notice that the newly grouped points of shape (m, n_sample, 3) are being subtracted from the points of shape (m, 1, 3):
https://github.com/POSTECH-CVLab/point-transformer/blob/8d2a38998f1ed8cd6d03fe1b671440724aa269c8/lib/pointops/functions/pointops.py#L93

What is the reason for doing this subtraction?

Also, specifically for the `TransitionDown` block of the PointTransformer architecture, this subtracted group of points is concatenated to the final grouped features (`use_xyz=True` option in the function call). Is this 100% correct? Because there is no mention of that in the PointTransformer paper.

Thank you very much!
Konstantinos

**Comment by QuanticDisaster** [comment]
From the way I see it, we subtract the positions of new points to the neighboors points (grouped_xyz). So I think the goal of this line is to return relatives positions in order to use them as features in the very first TransitionDown module instead of absolute position encoding

**Comment by ktertikas** [comment]
Thank you for the reply! 
The relative position formulation makes sense indeed. My main worry is that, in the paper, there is no mention whatsoever of the concatenation of this relative position in the `TransitionDown` module, so you would assume that this part is not needed. 
Is this part coming from the author's codebase? If yes, it would be good to know what relative improvements it gives in comparison to a non-concatenated feature vector...

**Comment by QuanticDisaster** [comment]
Indeed, the relative encoding is mentionned in the paper for transformer blocks (as well as the relative improvement for it) but not for the transition down module  but I guess you can't develop everything in it. For instance, the concatenation of multiples transformerblocks is not mentionned either and I initially thought there was only one per encoder/decoder. This code is indeed presented as the one from the first author. 

I would be glad to have a confirmation from the team who published the code though on this question (as well as the others still open) @chrockey

**Comment by chrockey** [comment]
Hi, @ktertikas  and @QuanticDisaster 

Sorry for the late reply.
I agree with you that there are missing details, which makes re-implementation difficult although using relative positions for downsampling modules has been widely used since SetAbstraction in PointNet++.
Therefore, we appreciate the authors of Point Transformer for providing this codebase to us and letting us make it public.

If I answer the main question from @ktertikas ("Is the relative position necessary for TransitionDown?") briefly, **it is**.
We have observed that removing the relative positional information in TransitionDown module degrades the performance.

Chunghyun

**Comment by ktertikas** [comment]
Hey @chrockey , thank you for the reply! It's a good thing to know that the lack of this relative positional information does indeed degrade the performance. Would you happen to have any relative numbers on, let's say, the task of point cloud classification with ModelNet40 as the dataset? If we assume that you reproduce the 93.7% test accuracy reported in the paper, what test accuracy would you expect without this relative positional information?

Thanks again for your insights!

Konstantinos

**Comment by chrockey** [comment]
Hi @ktertikas,

Unfortunately, we don't have any data related to ModelNet40.
We are still failing to reproduce the performance of Point Transformer (93.7) on ModelNet40.
We will add ModelNet40 codes to our codebase as soon as the numbers are reproduced :).

Chunghyun

**Comment by ktertikas** [comment]
Hi @chrockey , thank you for the reply. 
Looking around at other repositories and implementations, your observation seems consistent. I have also tried reproducing the performance of Point Transformer on ModelNet40, but have not been able to reach these numbers, on a custom implementation. Will be checking your repo for a reproduction in the future :)

Konstantinos
