### ISSUE TITLE
use two GPUs (Titan 24g) 

### ISSUE THREAD

**Issue by pointuser** [POSTECH-CVLab/point-transformer#48]
Hello, thank you very much for your code. I have a question. I hope you can help me. If I use two GPUs (Titan 24g), can I achieve the performance of (Miou 70)?
If possible, what do you think about the settings of parameters such as (batch size, LR) and network layers?
We look forward to your reply

**Comment by EricLina** [comment]
Hello! How about your result on two GPU?
